# Generated by Django 5.1.6 on 2025-02-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.JSONField()),
                ('instructions', models.JSONField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('servings', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=2083, null=True)),
                ('website', models.URLField(blank=True, max_length=2083, null=True)),
            ],
        ),
    ]
