# Generated by Django 5.1.6 on 2025-02-24 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recipe_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
